<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php print $this->get('title'); ?></title>
<link
	href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"
	rel="stylesheet">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<link
	href="<?php print route('resources','styles',array('id'=>'main'));?>"
	rel="stylesheet">

<style>
* {
	text-align: left;
}

.contento-template {
	padding: 40px 15px;
	text-align: center;
}

.panel {
	margin-top: 20px;
}

table .txt{
	vertical-align: middle !important;
}
</style>

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script
		src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="<?php print route('resources','d3');?>"></script>
	<script 
		src="<?php print route('resources','js',array('name'=>'bootstrap.file-input.js'));?>"></script>
</head>
<body>
	<?php if($this->has('nav', FALSE)): ?>
	<?php $this->partial('nav', array('nav' => $this->get('nav'))); ?>
	<?php endif; ?>
	<div class="container">
		<div class="contento-template">
			<div class="row">
				<h1 class="col-lg-12 col-sm-12">
					<?php print $this->get('title'); ?>
				</h1>
			</div>
			<?php if($this->has('breadcrumbs')): ?>
			<div class="row">
				<div class="col-lg-12">
					<?php $this->partial('breadcrumbs', array('breadcrumbs' => $this->get('breadcrumbs',array()))); ?>
				</div>
			</div>
			<?php endif; ?>
			<div class="row">
				<div class="col-lg-12">
					<?php $this->partial('actions', array('actions' => $this->get('actions', array()), 'actions_select' => $this->get('actions_select', ''))); ?>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<?php $this->partial('messages', array('messages'=> isset($_SESSION['messages']) ? $_SESSION['messages'] : array())); ?>
				</div>
			</div>
			<div class="content page-<?php $this->spit('page'); ?> row">
				<div class="col-lg-12">
					<?php $this->partial($this->get('page'), $this->get('data', array())); ?>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
