<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar" aria-expanded="false"
				aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php print route(); ?>">licence picker</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
		<ul class="nav navbar-nav  navbar-right">
			<li><a class="ontology-link" href="<?php print route('ontology');?>"><small>Licence Picker Ontology</small></a></li>
		</ul>
		</div>
		<?php /* ?>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Items <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
			            <li><a href="<?php print route('items', 'types'); ?>">Item collections</a></li>
			            <li><a href="<?php print route('items', 'newtype'); ?>">New collection</a></li>
			            <li><a href="<?php print route('items', 'additems'); ?>">Add items</a></li>
			        </ul>
				</li>
				<li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Contexts <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="<?php print route('contexts','list'); ?>">List of contexts</a></li>
		            <li><a href="<?php print route('contexts','new'); ?>">New context</a></li>
		            <li class="divider"></li>
		            <li><a href="<?php print route('contexts','import'); ?>">Import</a></li>
		            <li><a href="<?php print route('contexts','export'); ?>">Export</a></li>
		          </ul>
		        </li>
				<li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Taxonomies <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="<?php print route('taxonomies','list'); ?>">List of taxonomies</a></li>
		            <li class="divider"></li>
		            <li><a href="<?php print route('taxonomies','export'); ?>">Export</a></li>
		          </ul>
		        </li>
			</ul>
			<?php if($this->has('user')): ?>
			<?php $u = $this->get('user'); ?>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Signed in as <strong><?php print $u['name']?></strong> <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
			            <li><a href="<?php print route('default', 'logout'); ?>">Logout</a></li>
			        </ul>
				</li>
			</ul>
				
			<?php endif; ?>
		</div>
		<?php */ ?>
		<!--/.nav-collapse -->
	</div>
</nav>
